/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kasir;

import java.sql.*;
import lib.*;

/**
 *
 * @author ashary
 */
public final class Admin extends javax.swing.JFrame {
    
    private Connection conn;
    private Statement stmt;
    private ResultSet rs;

    /**
     * Creates new form Dashboard
     */
    public Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AdminMenuBar = new javax.swing.JMenuBar();
        UserMenu = new javax.swing.JMenu();
        AddUser = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        AccountMenu = new javax.swing.JMenu();
        OrderMenu = new javax.swing.JMenu();
        TransaksiMenu = new javax.swing.JMenu();
        LaporanMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kasir");

        UserMenu.setText("User");

        AddUser.setText("Add User");
        UserMenu.add(AddUser);

        jMenuItem1.setText("Manage User");
        UserMenu.add(jMenuItem1);

        AdminMenuBar.add(UserMenu);

        AccountMenu.setText("Menu");
        AccountMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AccountMenuMouseClicked(evt);
            }
        });
        AdminMenuBar.add(AccountMenu);

        OrderMenu.setText("Order");
        AdminMenuBar.add(OrderMenu);

        TransaksiMenu.setText("Transaksi");
        AdminMenuBar.add(TransaksiMenu);

        LaporanMenu.setText("Laporan");
        AdminMenuBar.add(LaporanMenu);

        setJMenuBar(AdminMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 606, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 303, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AccountMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccountMenuMouseClicked
        // TODO add your handling code here:
        new Account(this, true).setVisible(true);
    }//GEN-LAST:event_AccountMenuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Admin().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AccountMenu;
    private javax.swing.JMenuItem AddUser;
    private javax.swing.JMenuBar AdminMenuBar;
    private javax.swing.JMenu LaporanMenu;
    private javax.swing.JMenu OrderMenu;
    private javax.swing.JMenu TransaksiMenu;
    private javax.swing.JMenu UserMenu;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
