/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kasir;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.logging.*;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import lib.*;

/**
 *
 * @author ashary
 */
public final class Pelanggan extends javax.swing.JFrame {
    
    private Connection conn;
    private Statement stmt;
    private PreparedStatement pstmt;
    private ResultSet rs;
    

    /**
     * Creates new form Pelanggan
     */
    public Pelanggan() {
        initComponents();
        showDataToTable();

        try {
            if (Login.id_meja > 0) {
                NomorMeja.setText(Integer.toString(Login.id_meja));
            } else {
                conn = Database.getCon();
                stmt = conn.createStatement();
                rs = stmt.executeQuery("SELECT id_meja FROM `meja` WHERE `status` = 1 ORDER BY RAND() LIMIT 1");
                while (rs.next()) {
                    stmt.executeUpdate("UPDATE `meja` SET `status` = 0 WHERE `id_meja` = " + rs.getString("id_meja") );
                    stmt.executeUpdate("UPDATE `user` SET `id_meja` = " + rs.getString("id_meja") + " WHERE `id_user` = " + Login.id);
                    NomorMeja.setText(rs.getString("id_meja"));
                    Login.id_meja = rs.getInt("id_meja");
                }
                rs.close();
                stmt.close();
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Pelanggan.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    public void showDataToTable() {
        try {
            conn = Database.getCon();
            stmt = conn.createStatement();
            DefaultTableModel tb = new DefaultTableModel() {
                @Override
                public boolean isCellEditable(int i, int i1) {
                    return false; //To change body of generated methods, choose Tools | Templates.
                }
            };
            tb.addColumn("No");
            tb.addColumn("Nama");
            tb.addColumn("Harga");
            tb.addColumn("Status");
            TableBarang.setModel(tb);
            TableBarang.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            TableBarang.setDragEnabled(false);
            rs = stmt.executeQuery("SELECT * FROM `masakan`");
            while (rs.next()) {
                tb.addRow(new Object[]{
                    rs.getString("id_masakan"),
                    rs.getString("nama_masakan"),
                    rs.getString("harga"),
                    rs.getInt("status_masakan") == 1 ? "Tersedia" : "Habis"
                });
            }
            rs.close();
            stmt.close();
        } catch (SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(
                Level.SEVERE, 
                "Data tidak dapat ditampilkan. {0}", 
                ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TableBarang = new javax.swing.JTable();
        Pesan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        NomorMeja = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        Logout = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TableBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableBarang.getTableHeader().setReorderingAllowed(false);
        TableBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableBarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableBarang);

        Pesan.setText("Pesan");
        Pesan.setEnabled(false);
        Pesan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PesanMouseClicked(evt);
            }
        });
        Pesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesanActionPerformed(evt);
            }
        });

        jLabel1.setText("Nomor Meja");

        NomorMeja.setEnabled(false);
        NomorMeja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomorMejaActionPerformed(evt);
            }
        });

        Logout.setText("Keluar");
        jMenuBar1.add(Logout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Pesan)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NomorMeja, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(NomorMeja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Pesan)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TableBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableBarangMouseClicked
        // TODO add your handling code here:
        TableModel table = TableBarang.getModel();
        int row = TableBarang.getSelectedRow();
        if (table.getValueAt(row, 3).toString().equals("Tersedia")) {
            Pesan.setEnabled(true);
        }
    }//GEN-LAST:event_TableBarangMouseClicked

    private void PesanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PesanMouseClicked
        // TODO add your handling code here:
        TableModel table = TableBarang.getModel();
        int row = TableBarang.getSelectedRow();
        String input;
        int jumlah = 1;
        do {
            input = JOptionPane.showInputDialog("Jumlah pesanan:  ");
            if (input.matches("^[1-9]*$")) {
                jumlah = Integer.parseInt(input);
            }
        } while (!input.matches("^[1-9]*$"));

        try {
            java.util.Date dt = new java.util.Date();
            java.text.SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");

           String currentTime = sdf.format(dt);
            conn = Database.getCon();
            pstmt = conn.prepareStatement("INSERT INTO `tbl_order` (`id_meja`, `tanggal`, `id_user`, `status_order`) VALUES (?, ?, ?, ?)", Statement.RETURN_GENERATED_KEYS);
            pstmt.setInt(1, Login.id_meja);
            pstmt.setString(2, currentTime);
            pstmt.setInt(3, Login.id);
            pstmt.setInt(4, 1);
            pstmt.executeUpdate();
            rs = pstmt.getGeneratedKeys();
            if(rs.next()){
		int id = rs.getInt(1);
                pstmt = conn.prepareStatement("INSERT INTO `detail_order` (`id_order`, `id_makanan`, `jumlah`) VALUES (?, ?, ?)");
                pstmt.setInt(1, id);
                pstmt.setInt(2, Integer.parseInt((String) table.getValueAt(row, 0)));
                pstmt.setInt(3, jumlah);
                pstmt.executeUpdate();
            }
        } catch (SQLException ex) {
            Logger.getLogger(Pelanggan.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        int confirm;
        confirm = JOptionPane.showConfirmDialog(null, "Apakah anda ingin memesan lagi ?", "Pesan lagi ?", JOptionPane.YES_NO_OPTION);
        
        if (confirm == 1) {
            new WaitingOrder().setVisible(true);
            dispose();
        } else {
            // s
        }
    }//GEN-LAST:event_PesanMouseClicked

    private void PesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PesanActionPerformed

    private void NomorMejaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomorMejaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomorMejaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Pelanggan().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Logout;
    private javax.swing.JTextField NomorMeja;
    private javax.swing.JButton Pesan;
    private javax.swing.JTable TableBarang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
